  version: '3'
  services:
    server:
      build:
        context: ./server
      ports:
        - "5000:5000"
      networks:
        - urlshortner-network
      depends_on:
        - mongo
      environment:
        - DB=mongodb://mongo:27017/urlshortner_database

    client:
      build:
        context: ./client
      ports:
        - "8000:80"
      networks:
        - urlshortner-network
      depends_on:
        - server
      environment:
        - REACT_APP_API_URL=http://server:5000/api

    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      networks:
            - urlshortner-network


  networks:
    urlshortner-network:
      driver: bridge

