  version: '3'
  services:
    server:
      build:
        context: ./server
      ports:
        - "5000:5000"
      networks:
        - urlshortner-network

    client:
      build:
        context: ./client
      ports:
        - "8000:81"

    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      networks:
            - urlshortner-network


  networks:
    urlshortner-network:
      driver: bridge

