  version: '3'
  services:
    server:
      build:
        context: ./server
      ports:
        - "5000:5000"
      networks:
        - urlshortner-network
      depends_on:
        - mongo
      environment:
        - DB=mongodb://mongo:27017/urlshortner_database

      restart: unless-stopped
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s

    client:
      build:
        context: ./client
      ports:
        - "8000:80"
      networks:
        - urlshortner-network
      depends_on:
        - server
      environment:
        - REACT_APP_API_URL=http://server:5000/api

      restart: unless-stopped

    mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
      networks:
            - urlshortner-network
      volumes:
        - mongo-data:/data/db
      restart: unless-stopped
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 20s


  networks:
    urlshortner-network:
      driver: bridge

  volumes:
    mongo-data:
      driver: local


