all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/var/lib/jenkins/.ssh/aws-key.pem"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    
  children:
    app_servers:
      hosts:
        url_shortener:
          ansible_host: "{{ app_host_ip }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "/var/lib/jenkins/.ssh/aws-key.pem"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"